
* board 

** in

** started

*** build dialog


*** DONE run app from pytest
    CLOSED: [2019-09-18 śro 20:04]

*** DONE run app from command line
    CLOSED: [2019-09-18 śro 20:04]

*** DONE set update action to status bar for clicking buttons
    CLOSED: [2019-09-18 śro 18:41]

*** DONE create instance object manager
    CLOSED: [2019-09-18 śro 18:41]

** done

*** DONE list out all needed objects

**** objects 
- menu
- toolbar
- main window : fill x fill y
- status bar

***** in main window: 
- 1, 2, 5, 6, 9, 10, 15, 16, 20 buttons

***** in toolbar:
- 4 buttons

*** DONE write all objects
    CLOSED: [2019-09-15 nie 19:37]

*** DONE add toolbar
    CLOSED: [2019-09-15 nie 19:36]

*** DONE add main widget
    CLOSED: [2019-09-15 nie 19:36]

*** DONE finish adding simple dialog
    CLOSED: [2019-09-15 nie 19:37]

* architecture
*** objects 
- menu
- toolbar
- main window : fill x fill y
- status bar

**** in main window: 
- 1, 2, 5, 6, 9, 10, 15, 16, 20 buttons

**** in toolbar:
 - 4 buttons

* diary

** <2019-09-13 pią>
today i started to think about the way
i should start this project

i need to start from the test.
but to how i should start?

skeleton is hanging all the meat.
lets build a skeleton of the app
and then we see.

i will build all the components
in a static state. this will
also include all possible states.

** <2019-09-14 sob>
the skeleton was build
but aligning all objects inside a frame
is complicated

i will try now to use gtk3 with pygobjects

** <2019-09-15 nie>

im reading the gtk manual but i have to write stuff up
and see where this will take me


also i need to run the git inside here

there where apps written in python in gtk3.
where are they and why i dont have them on my hard drive?

** <2019-09-18 śro>

so today i will come back and do some
projects

what i need are diagrams of what am i doing

i need to install dia
dia was installed but i did diagrams by hand faster

i made simple register based on decorators
it holds objects and allows me to send messages
with status bar from other buttons

doing so i found a set of decorators code that
can be useful during work

